# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20170415_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
