# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20170408_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='path',
            field=models.FilePathField(unique=True),
        ),
    ]
