# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20170417_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filelink',
            old_name='shared_permission',
            new_name='share_permission',
        ),
        migrations.RenameField(
            model_name='folderlink',
            old_name='shared_permission',
            new_name='share_permission',
        ),
        migrations.AlterField(
            model_name='filelink',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='folderlink',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
