# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20170603_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filelink',
            old_name='share_permission',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='folderlink',
            old_name='share_permission',
            new_name='permission',
        ),
    ]
