# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20170603_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='filelink',
            name='updated_at',
        ),
    ]
