# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_auto_20170611_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelink',
            name='permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='share.Permission'),
        ),
        migrations.AlterField(
            model_name='folderlink',
            name='permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='share.Permission'),
        ),
    ]
